Repository embulk/embulk, pull requests merged in 2019-03, with the labels that each got.

#1116 Leave a link to GitHub Releases from https://www.embulk.org/docs/release.html
  embulk-docs/src/release.rst
Labels: document:user

#1115 Remove general help of `-R` options to have only `-R--dev`
  embulk-core/src/main/java/org/embulk/cli/EmbulkRun.java
Labels: document:user

#1126 Bump up to v0.9.17-SNAPSHOT
  build.gradle
Labels: bump

#1123 Load Apache Commons CLI library in a separate ClassLoader
  build.gradle
  embulk-core/build.gradle
  embulk-core/src/main/java/org/embulk/cli/EmbulkRun.java
  embulk-core/src/main/java/org/embulk/cli/parse/AbstractHelpLineDefinition.java
  embulk-core/src/main/java/org/embulk/cli/parse/HelpMessageLineDefinition.java
  embulk-core/src/main/java/org/embulk/cli/parse/OptionDefinition.java
  embulk-core/src/main/java/org/embulk/deps/EmbulkDependencyClassLoaders.java
  embulk-core/src/main/java/org/embulk/deps/EmbulkSelfContainedJarFiles.java
  embulk-core/src/main/java/org/embulk/deps/cli/AbstractHelpLineDefinition.java
  embulk-core/src/main/java/org/embulk/deps/cli/CliParser.java
  embulk-core/src/main/java/org/embulk/deps/cli/EmbulkCommandLineHelpRequired.java
  embulk-core/src/main/java/org/embulk/deps/cli/EmbulkCommandLineParseException.java
  embulk-core/src/main/java/org/embulk/deps/cli/HelpMessageLineDefinition.java
  embulk-core/src/main/java/org/embulk/deps/cli/OptionBehavior.java
  embulk-core/src/main/java/org/embulk/deps/cli/OptionDefinition.java
  embulk-deps/cli/build.gradle
  embulk-deps/cli/config/checkstyle/suppressions.xml
  embulk-deps/cli/src/main/java/org/embulk/deps/cli/CliHelpFormatterWithHelpMessages.java
  embulk-deps/cli/src/main/java/org/embulk/deps/cli/CliOptionsWithHelpMessages.java
  embulk-deps/cli/src/main/java/org/embulk/deps/cli/CliParserImpl.java
  embulk-deps/cli/src/main/java/org/embulk/deps/cli/HelpMessageAsCliOption.java
  embulk-deps/cli/src/main/java/org/embulk/deps/cli/HelpMessageLineDefinitionImpl.java
  embulk-deps/cli/src/main/java/org/embulk/deps/cli/OptionDefinitionImpl.java
  settings.gradle
Labels: kaizen, topic:dependency-classloader

#1127 Load Apache Velocity in the sub ClassLoader
  embulk-core/build.gradle
  embulk-core/src/main/java/org/embulk/cli/EmbulkNew.java
  embulk-core/src/main/java/org/embulk/deps/cli/VelocityEngineDelegate.java
  embulk-deps/cli/build.gradle
  embulk-deps/cli/src/main/java/org/embulk/deps/cli/VelocityEngineDelegateImpl.java
Labels: kaizen, topic:dependency-classloader

#1111 Unsupport nested-JAR style JAR plugins.
  embulk-core/src/main/java/org/embulk/plugin/PluginClassLoader.java
  embulk-core/src/main/java/org/embulk/plugin/PluginClassLoaderFactory.java
  embulk-core/src/main/java/org/embulk/plugin/PluginClassLoaderModule.java
  embulk-core/src/main/java/org/embulk/plugin/jar/JarPluginLoader.java
  embulk-core/src/test/java/org/embulk/plugin/jar/TestJarPluginLoader.java
  test-helpers/build.gradle
Labels: deprecation, kaizen, topic:pure-java-plugins

#1131 Test with Logback so that logs can be checked
  embulk-core/build.gradle
  embulk-standards/build.gradle
Labels: test

#1133 Provide system config options to disable selected standard plugins
  embulk-standards/src/main/java/org/embulk/standards/StandardPluginExtension.java
  embulk-standards/src/main/java/org/embulk/standards/StandardPluginModule.java
Labels: kaizen

#1132 Self-update from https://dl.embulk.org
  embulk-core/src/main/java/org/embulk/cli/EmbulkRun.java
  embulk-core/src/main/java/org/embulk/cli/EmbulkSelfUpdate.java
  embulk-core/src/main/java/org/embulk/cli/SelfUpdate.java
Labels: kaizen
