Repository embulk/embulk, pull requests merged in 2020-11, with the labels that each got.

#1333 Refactor command line parsing to retrieve Embulk System Properties in the very beginning
  embulk-core/src/main/java/org/embulk/cli/CliLogbackConfigurator.java
  embulk-core/src/main/java/org/embulk/cli/Command.java
  embulk-core/src/main/java/org/embulk/cli/CommandLine.java
  embulk-core/src/main/java/org/embulk/cli/EmbulkArguments.java
  embulk-core/src/main/java/org/embulk/cli/EmbulkCommandLine.java
  embulk-core/src/main/java/org/embulk/cli/EmbulkCommandLineException.java
  embulk-core/src/main/java/org/embulk/cli/EmbulkRun.java
  embulk-core/src/main/java/org/embulk/cli/EmbulkSubcommand.java
  embulk-core/src/main/java/org/embulk/cli/Main.java
  embulk-core/src/main/java/org/embulk/deps/cli/AbstractHelpLineDefinition.java
  embulk-core/src/main/java/org/embulk/deps/cli/CliParser.java
  embulk-core/src/main/java/org/embulk/deps/cli/CommandLineParser.java
  embulk-core/src/main/java/org/embulk/deps/cli/EmbulkCommandLineHelpRequired.java
  embulk-core/src/main/java/org/embulk/deps/cli/EmbulkCommandLineParseException.java
  embulk-core/src/main/java/org/embulk/deps/cli/OptionBehavior.java
  embulk-core/src/main/java/org/embulk/deps/cli/OptionDefinition.java
  embulk-deps/build.gradle
  embulk-deps/gradle/dependency-locks/compileClasspath.lockfile
  embulk-deps/gradle/dependency-locks/runtimeClasspath.lockfile
  embulk-deps/src/main/java/org/embulk/deps/cli/CliOptionsWithHelpMessages.java
  embulk-deps/src/main/java/org/embulk/deps/cli/CliParserImpl.java
  embulk-deps/src/main/java/org/embulk/deps/cli/CommandLineImpl.java
  embulk-deps/src/main/java/org/embulk/deps/cli/CommandLineParserImpl.java
  embulk-deps/src/main/java/org/embulk/deps/cli/CommandWriters.java
  embulk-deps/src/main/java/org/embulk/deps/cli/HelpFormatterWithPlaceholders.java
  embulk-deps/src/main/java/org/embulk/deps/cli/HelpMessageLineDefinitionImpl.java
  embulk-deps/src/main/java/org/embulk/deps/cli/OptionDefinitionImpl.java
  embulk-deps/src/main/java/org/embulk/deps/cli/OptionsWithPlaceholders.java
  embulk-deps/src/main/java/org/embulk/deps/cli/PlaceholderOption.java
  embulk-deps/src/test/java/org/embulk/deps/cli/TestCommandLineParserImpl.java
Labels: nitpicks-and-refactoring

#1334 Find Embulk's home-like directories: embulk_home, m2_repo, gem_home, and gem_path
  build.gradle
  embulk-core/src/main/java/org/embulk/cli/EmbulkRun.java
  embulk-core/src/main/java/org/embulk/cli/EmbulkSystemPropertiesBuilder.java
  embulk-core/src/main/java/org/embulk/cli/Main.java
  embulk-core/src/main/java/org/embulk/jruby/JRubyInitializer.java
  embulk-core/src/main/java/org/embulk/jruby/JRubyScriptingModule.java
  embulk-core/src/main/java/org/embulk/plugin/maven/MavenPluginSource.java
  embulk-core/src/test/java/org/embulk/jruby/TestJRubyInitializer.java
Labels: enhancement

#1339 Bump up to v0.10.21-SNAPSHOT
  build.gradle
Labels: bump

#1336 Use external JRuby optional
  build.gradle
  embulk-core/build.gradle
  embulk-core/gradle/dependency-locks/compileClasspath.lockfile
  embulk-core/gradle/dependency-locks/runtimeClasspath.lockfile
  embulk-core/src/main/java/org/embulk/EmbulkRunner.java
  embulk-core/src/main/java/org/embulk/cli/EmbulkRun.java
  embulk-core/src/main/java/org/embulk/jruby/JRubyClassLoader.java
  embulk-core/src/main/java/org/embulk/jruby/JRubyInitializer.java
  embulk-core/src/main/java/org/embulk/jruby/JRubyPluginSource.java
  embulk-core/src/main/java/org/embulk/jruby/JRubyScriptingModule.java
  embulk-core/src/main/java/org/embulk/jruby/LazyScriptingContainerDelegate.java
  embulk-core/src/main/ruby/embulk/page_builder.rb
  embulk-core/src/main/ruby/embulk/schema.rb
  embulk-core/src/test/java/org/embulk/jruby/TestJRubyInitializer.java
  embulk-core/src/test/ruby/vanilla/run-test.rb
  embulk-core/src/test/ruby/vanilla/test_schema.rb
  embulk-core/src/test/ruby/vanilla/time/test_timestamp_parser.rb
  embulk-deps/gradle/dependency-locks/compileClasspath.lockfile
  embulk-junit4/gradle/dependency-locks/compileClasspath.lockfile
  embulk-junit4/gradle/dependency-locks/runtimeClasspath.lockfile
  embulk-standards/build.gradle
  embulk-standards/gradle/dependency-locks/compileClasspath.lockfile
  embulk-standards/src/test/ruby/vanilla/run-test.rb
Labels: deprecation, large-change-or-large-impact, topic:dependency-classloader

#1338 Remove embedded gems: msgpack, bundler, liquid
  build.gradle
  embulk-core/build.gradle
  embulk-core/src/test/ruby/vanilla/run-test.rb
  embulk-standards/build.gradle
  embulk-standards/src/test/ruby/vanilla/run-test.rb
Labels: deprecation

#1346 Bump up to v0.10.22-SNAPSHOT
  build.gradle
Labels: bump

#1340 Remove msgpack-core from embulk-core as it is already in embulk-api
  embulk-core/build.gradle
Labels: nitpicks-and-refactoring

#1341 Move PreviewPrinter to embulk-deps
  embulk-core/src/main/java/org/embulk/EmbulkRunner.java
  embulk-core/src/main/java/org/embulk/command/VerticalPreviewPrinter.java
  embulk-core/src/main/java/org/embulk/deps/preview/PreviewPrinter.java
  embulk-deps/src/main/java/org/embulk/deps/preview/PreviewPrinterImpl.java
  embulk-deps/src/main/java/org/embulk/deps/preview/TablePreviewPrinter.java
  embulk-deps/src/main/java/org/embulk/deps/preview/ValueFormatter.java
  embulk-deps/src/main/java/org/embulk/deps/preview/VerticalPreviewPrinter.java
Labels: topic:dependency-classloader

#1342 Cleanup and refactor PluginClassLoader and its Factory
  embulk-core/src/main/java/org/embulk/plugin/PluginClassLoader.java
  embulk-core/src/main/java/org/embulk/plugin/PluginClassLoaderFactory.java
  embulk-core/src/main/java/org/embulk/plugin/PluginClassLoaderFactoryImpl.java
  embulk-core/src/main/java/org/embulk/plugin/jar/JarPluginLoader.java
Labels: nitpicks-and-refactoring

#1350 Bump up to v0.10.23-SNAPSHOT
  build.gradle
Labels: bump

#1349 Fix the mkbundle subcommand with bundler 2.1.4 (#1348)
  embulk-core/src/main/java/org/embulk/cli/EmbulkRun.java
Labels: bug
